### ISSUE TITLE
Armenian is missing in the list of languages for spellcheck

### ISSUE THREAD

**Issue by sedast** [brrd/Abricotine#157] opened 2017-02-15 13:01 UTC
Armenian is missing in the list of languages for spellcheck. Please add it to the list so that it may be possible to use the Armenian hunspell dictionary put in the dict folder. Thanks.

**Comment by brrd** [comment] 2017-03-06 20:41
What is your OS?
Did you actually try to copy the Armenian hunspell dictionary into the dict directory?

**Comment by sedast** [comment] 2017-03-07 09:51
Hi, Thomas

 

Yes, surely I copied the hunspell dictionary for Armenian. I'm using both Windows 8.1 and Ubuntu 16.04.

I've attached a screenshot from the dictionaries folder of Abricotine in Windows where you can see the folder for Armenian dictionary. But it doesn't show up in the list of languages for check spell so that I could choose and use it.

 

Best regards,

Seda

 

Sent: Tuesday, March 07, 2017 at 12:41 AM

**Comment by brrd** [comment] 2017-03-07 10:07
On Windows 8 hunspell dictionaries are actually useless (check [the doc](https://github.com/brrd/Abricotine/blob/master/docs/configuration.md#spell-checker-dictionaries)). But we'll try to improve this, see #134.

On Ubuntu it should work, though, but as I can see on your screenshot you are not dropping dictionaries in their correct location. From Abricotine menu, use Edit > Open Config Directory. User defined dictionaries must be copied there, into the dict subfolder. You need to restart the app to get the new dictionary in the Spelling menu.

**Comment by sedast** [comment] 2017-03-07 11:31
Nope, in Ubuntu it is in the correct folder as you can see in the screenshot attached, but Armenian doesn't show up in the list of languages in the application, as you can also see in the same screenshot.
![screenshot from 2017-03-07 15-23-53](https://cloud.githubusercontent.com/assets/25794302/23654663/28e32146-034b-11e7-88eb-a8d1d223971b.png)

**Comment by sedast** [comment] 2017-03-07 11:35
You've closed the issue before solving it.

**Comment by brrd** [comment] 2017-03-07 11:42
Where did you find this dictionary? Can you show the content of hy_HY?

**Comment by sedast** [comment] 2017-03-07 11:58
Thanks for reopening.
I don't remember where in the Internet I had downloaded the dictionaries. In fact, I have three versions of hunspell-dictionaries for Armenian. After your last message, I tried the two other versions also, thinking the problem is perhaps in the dictionary itself (I hadn't tried to change the dictionary before). I changed the dictionary, restarted the application, and no change in the list of languages. Armenian is not there.

As for the content of those dictionaries, if you mean the file names, they are the following:

1) hy_HY.aff
hy_HY.dic

2)Armenian (Eastern).aff
Armenian (Eastern).dic

3) hy_AM-v0.60.aff
hy_AM-v0.60.dic

**Comment by brrd** [comment] 2017-03-07 12:31
I can't find those dictionaries so I can't reproduce this issue.

Actually hy_HY does not exist in Mozilla's language mapping list but there is a hy_AM entry: https://github.com/mozilla/language-mapping-list/blob/master/language-mapping-list.js#L393
What is the difference between those two locales?
Can you try to rename hy_HY (dir and files) into hy_AM (in order to see if the issue comes from the langmap module)?

**Comment by sedast** [comment] 2017-03-07 13:48
Thanks a lot! It worked after changing the uppercase HY to AM in the name (but how strange it is that in case of Armenian two different abbreviations should be used).

**Comment by sedast** [comment] 2017-03-07 13:51
AM is the Armenian domain ending (www.XXX.am). While HY is the language code abbreviation. I have no idea why these two are mixed in this particular case.

**Comment by brrd** [comment] 2017-03-07 18:06
The first code is the language (ISO 639, https://en.wikipedia.org/wiki/ISO_639) the second is the country (ISO 3166, https://en.wikipedia.org/wiki/ISO_3166). "hy" is the language while the country is "am", so hy_AM is the correct code here.

But I think we should display something in the menu even when the language name is not found in langmap.

**Comment by brrd** [comment] 2017-03-07 18:11
I'm closing this issue. I created #157 to improve the display of dictionaries in the menu.

**Closed by brrd** 2017-03-07 18:11 UTC
Labels: bug, need info
