### ISSUE TITLE
Problem running on ubuntu 15.10

### ISSUE THREAD

**Issue by Abdulla2** [brrd/Abricotine#20] opened 2016-02-22 16:47 UTC
When I tried to run it 
the following error was shown
```
A JavaScript error occurred in the main process
Uncaught Exception:
Error: /home/abdulla/apps/Abricotine-linux-ia32/resources/app.asar.unpacked/node_modules/spellchecker/build/Release/spellchecker.node: wrong ELF class: ELFCLASS64
    at Error (native)
    at Object.module.(anonymous function) (ATOM_SHELL_ASAR.js:137:20)
    at Object.module.(anonymous function) [as .node] (ATOM_SHELL_ASAR.js:148:18)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/home/abdulla/apps/Abricotine-linux-ia32/resources/app.asar/node_modules/spellchecker/lib/spellchecker.js:2:16)
    at Module._compile (module.js:434:26)
    at Object.Module._extensions..js (module.js:452:10)

```

**Comment by alexcheninfo** [comment] 2016-02-22 17:17
@Abdulla2  I think you either downloaded the 64 bit version and ran it on a 32 bit machine or the other way around. Try installing another version.

**Comment by Abdulla2** [comment] 2016-02-22 17:37
no my laptop is 32bit and I downloaded Abricotine-linux-ia32 @alexcheninfo

**Comment by alexcheninfo** [comment] 2016-02-22 17:38
@Abdulla2  Oh, I see. Then let's wait for the developers to respond. I'm waiting for their reply too!

**Comment by brrd** [comment] 2016-02-23 14:37
This issue is a duplicate of #6.

**Closed by brrd** 2016-02-23 14:37 UTC
