### ISSUE TITLE
Setext style headers not properly previewed

### ISSUE THREAD

**Issue by pilem** [brrd/Abricotine#131] opened 2016-11-23 17:53 UTC
Level 1 and 2 headers written in setext style, i.e. underlined with equal or hyphen signs, are not properly previewed. The text is not large and bold as it should, but the underline is. They are correctly identified in the table of content and are correctly exported in html.

![capture du 2016-11-23 12-37-44](https://cloud.githubusercontent.com/assets/23705272/20572662/5aba9172-b17a-11e6-9c5c-5ded50389911.png)

Using v.0.4.0. on Ubuntu 16.04, installed with the provided deb package.

Also, great software, Abricotine is exactly what I was looking for.  I really like the idea of not hiding the markdown syntax and edit in a preview mode.

**Comment by brrd** [comment] 2016-11-23 18:02
Hi, it's obviously a duplicate of #57

**Closed by brrd** 2016-11-23 18:02 UTC

**Comment by pilem** [comment] 2016-11-23 18:23
Yes, you're right. I don't know why I mist it. Sorry for the false issue.

-------- Message d'origine --------
De : Thomas Brouard <notifications@github.com> 
Date : 2016/11/23  13:02  (GMT-05:00) 
À : brrd/Abricotine <Abricotine@noreply.github.com> 
Cc : pilem <pierre.lemay@gmail.com>, Author <author@noreply.github.com> 
Objet : Re: [brrd/Abricotine] Setext style headers not properly previewed
  (#131) 

Hi, it's obviously a duplicate of #57

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/brrd/Abricotine","title":"brrd/Abricotine","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/brrd/Abricotine"}},"updates":{"snippets":[{"icon":"PERSON","message":"@brrd in #131: Hi, it's obviously a duplicate of #57"}],"action":{"name":"View Issue","url":"https://github.com/brrd/Abricotine/issues/131#issuecomment-262588785"}}}
