### ISSUE TITLE
Adding preview for links [enhancement]

### ISSUE THREAD

**Issue by Julianoe** [brrd/Abricotine#260] opened 2019-05-31 23:16 UTC
Would it be difficult to add a "closed down" state/preview for the link element, and the associated menu toggle for links?

I'll try to get my head around the code of the program if i can but i'm not familiar with such a language so, no promises

**Comment by brrd** [comment] 2019-06-03 08:56
What is a "closed down" state/preview?

**Comment by Julianoe** [comment] 2019-06-03 11:44
Sorry if my post was not clear enough. 

By "closed down" link i meant that once the link is set with [ my anchor ] ( https://www.wikiwand.com/en/Samuel_L._Jackson ) it could appear like a standard HTML link so the content is not visually polluted by long links and whatnot. 
Typically i think i remember it's how Typora and some other editors do it. 

When you click the link it displays it in markdown format again.

**Comment by brrd** [comment] 2019-06-03 12:11
OK so this is a duplicate of #158.

**Closed by brrd** 2019-06-03 12:11 UTC

**Comment by Julianoe** [comment] 2019-06-03 14:34
My bad! i did not stumble onto this other issue while searching. Thanks for the answers though!
